--- #YAML:1.0
name: all
version: 0.5
license: perl
distribution_type: module
requires:
  File::Spec: 0.01
recommends: {}
build_requires: {}
conflicts: {}
provides:
  all:
    file: lib/all.pm
    version: 0.5
generated_by: Module::Build version 0.20
